// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wznknuyskxhddjpvuwqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bmtudXlza3hoZGRqcHZ1d3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDExNDksImV4cCI6MjA1NzE3NzE0OX0.L3LMLd0Vj5Iki5k7ZycEBEVKM5QUHAOV0oDlrzr8lTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);